### ISSUE TITLE
flet{,rec} indentation is undesirable

### ISSUE THREAD

**Issue by yurrriq** [lfe/lfe#137]
Update `lfe-mode` to indent `flet` and `fletrec` forms similar to how `clojure-mode` indents `letfn` forms.
#### Current

``` lfe
(flet ((replace (smap coll)
                (lists:map (lambda (x) (maps:get x smap x)) coll)))
  ...)
```
#### Desired

``` lfe
(flet ((replace (smap coll)
         (lists:map (lambda (x) (maps:get x smap x)) coll)))
  ...)

;; (defun replace (smap coll)
;;   (lists:map (lambda (x) (maps:get x smap x)) coll))

;;; == Clojure ==================================
;; (letfn [(replace [smap coll]
;;           (map (fn [x] (get smap x x)) coll))]
;;   ...)
```

@rvirding, I'm making this issue as a reminder to myself, if that's alright.

PS I have some updates to `inferior-lfe` [in the works](https://github.com/rvirding/lfe/compare/develop...yurrriq:inferior-lfe).

**Comment by rvirding** [comment]
No worries, do it when you can. I have made a small changes in the font handling which changes the colour of some things. It should not affect you however.

**Comment by yurrriq** [comment]
Is there a particular reason to use the custom scheme-mode-base indention function instead of a customized `cl-indent-function`? I feel like most of the trickier issues are already solved there, namely backtracking indents.

**Comment by rvirding** [comment]
This was quite a while back but as far as I can remember I didn't
explicitly use the scheme mode based indentation function. And if I did
then it probably was because back in the beginning LFE was actually a bit
scheme influenced, before we went lisp-2+ and it became more CL like. Some
of the original schemish macros are still there.

I will take a look at the CL stuff and see if we can migrate towards that.

**Comment by oubiwann** [comment]
:+1: 

I've found some of the scheme-isms in LFE mode to be a little distracting :-)

**Comment by yurrriq** [comment]
Ah, right. I had a `macroexpand` yield a `define-function` the other day and it took me a second to figure out why.

Sounds good, @rvirding. Keep us apprised of your findings?

**Comment by phoe** [comment]
Ping. This issue still affects me and it makes my eyes go pretty crazy after Common Lisp programming. :stuck_out_tongue: 
![zrzut ekranu z 2017-05-25 17-05-00](https://cloud.githubusercontent.com/assets/15045546/26456275/e4f049e0-416c-11e7-9c3f-7464820a05e0.png)
